export const EXERCISE = "EXERCISE";
export const ADDEXERCISEINLIST = "ADDEXERCISEINLIST";
export const ADDWORK = "ADDWORK";
export const ADDEXERCISE = "ADDEXERXISE";
export const CLEANWORK = "CLEANWORK";
export const DELETE_EXERCISE = "DELETE_EXERCISE";
